services:
  postgres:
    image: postgres:17-alpine
    container_name: attendance_db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "280410"
      POSTGRES_DB: attendance_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - attendance-net

  api:
    build: .
    container_name: attendance_api_container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/attendance_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "280410"
      TZ: "America/Lima"
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - attendance-net

volumes:
  postgres_data:

networks:
  attendance-net:
    driver: bridge